pbr: update to latest

diff --git a/net/pbr/Makefile b/net/pbr/Makefile
--- a/net/pbr/Makefile
+++ b/net/pbr/Makefile
@@ -1,64 +1,67 @@
-# Copyright 2017-2022 Stan Grishin (stangri@melmac.ca)
+# Copyright 2017-2023 Stan Grishin (stangri@melmac.ca)
 # This is free software, licensed under the GNU General Public License v3.
 
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=pbr
-PKG_VERSION:=1.1.1
-PKG_RELEASE:=7
+PKG_VERSION:=1.1.3
+PKG_RELEASE:=2
 PKG_LICENSE:=GPL-3.0-or-later
 PKG_MAINTAINER:=Stan Grishin <stangri@melmac.ca>
 
 include $(INCLUDE_DIR)/package.mk
 
-define Package/pbr/default
+define Package/pbr/Default
   SECTION:=net
   CATEGORY:=Network
-  SUBMENU:=VPN
+  SUBMENU:=Routing and Redirection
   TITLE:=Policy Based Routing Service
   URL:=https://docs.openwrt.melmac.net/pbr/
   DEPENDS:=+ip-full +jshn +jsonfilter +resolveip
+	DEPENDS+=+BUSYBOX_DEFAULT_AWK:gawk
+	DEPENDS+=+BUSYBOX_DEFAULT_GREP:grep
+	DEPENDS+=+BUSYBOX_DEFAULT_SED:sed
   CONFLICTS:=vpnbypass vpn-policy-routing
   PKGARCH:=all
 endef
 
 define Package/pbr
-$(call Package/pbr/default)
-	TITLE+= with nft/nft set support
-	DEPENDS+=+firewall4 +kmod-nft-core +kmod-nft-nat +nftables-json
-	VARIANT:=nftables
-	PROVIDES:=vpnbypass vpn-policy-routing
+$(call Package/pbr/Default)
+  TITLE+= with nft/nft set support
+  DEPENDS+=+kmod-nft-core +kmod-nft-nat +nftables-json
+  VARIANT:=nftables
+  PROVIDES:=vpnbypass vpn-policy-routing
 endef
 
 define Package/pbr-iptables
-$(call Package/pbr/default)
-	TITLE+= with iptables/ipset support
-	DEPENDS+=+ipset +iptables +kmod-ipt-ipset +iptables-mod-ipopt
-	VARIANT:=iptables
-	PROVIDES:=pbr
-	DEFAULT_VARIANT:=1
+$(call Package/pbr/Default)
+  TITLE+= with iptables/ipset support
+  DEPENDS+=+ipset +iptables +kmod-ipt-ipset +iptables-mod-ipopt
+  VARIANT:=iptables
+  PROVIDES:=pbr
+  DEFAULT_VARIANT:=1
 endef
 
 define Package/pbr-netifd
-$(call Package/pbr/default)
-	TITLE+= with netifd support
-	VARIANT:=netifd
-	PROVIDES:=pbr
+$(call Package/pbr/Default)
+  TITLE+= with netifd support
+  VARIANT:=netifd
+  PROVIDES:=pbr
 endef
 
 define Package/pbr/description
 This service enables policy-based routing for WAN interfaces and various VPN tunnels.
-This version supports OpenWrt with both fw3/ipset/iptables and fw4/nft.
+This version supports OpenWrt with both firewall3/ipset/iptables and firewall4/nft.
 endef
 
 define Package/pbr-iptables/description
 This service enables policy-based routing for WAN interfaces and various VPN tunnels.
-This version supports OpenWrt with fw3/ipset/iptables.
+This version supports OpenWrt with firewall3/ipset/iptables.
 endef
 
 define Package/pbr-netifd/description
 This service enables policy-based routing for WAN interfaces and various VPN tunnels.
-This version supports OpenWrt with both fw3/ipset/iptables and fw4/nft.
+This version supports OpenWrt with both firewall3/ipset/iptables and firewall4/nft.
 This version uses OpenWrt native netifd/tables to set up interfaces. This is WIP.
 endef
 
@@ -77,16 +80,16 @@ endef
 
 define Package/pbr/default/install
 	$(INSTALL_DIR) $(1)/etc/init.d
-	$(INSTALL_BIN) ./files/etc/init.d/pbr.init $(1)/etc/init.d/pbr
+	$(INSTALL_BIN) ./files/etc/init.d/pbr $(1)/etc/init.d/pbr
 	$(SED) "s|^\(readonly PKG_VERSION\).*|\1='$(PKG_VERSION)-$(PKG_RELEASE)'|" $(1)/etc/init.d/pbr
 	$(INSTALL_DIR) $(1)/etc/hotplug.d/iface
-	$(INSTALL_DATA) ./files/etc/hotplug.d/iface/70-pbr $(1)/etc/hotplug.d/iface/70-pbr
 	$(INSTALL_DIR) $(1)/etc/uci-defaults
 	$(INSTALL_BIN)  ./files/etc/uci-defaults/90-pbr $(1)/etc/uci-defaults/90-pbr
 	$(INSTALL_DIR) $(1)/usr/share/pbr
 	$(INSTALL_DATA) ./files/usr/share/pbr/pbr.user.aws $(1)/usr/share/pbr/pbr.user.aws
 	$(INSTALL_DATA) ./files/usr/share/pbr/pbr.user.netflix $(1)/usr/share/pbr/pbr.user.netflix
 endef
+#	$(INSTALL_DATA) ./files/etc/hotplug.d/iface/70-pbr $(1)/etc/hotplug.d/iface/70-pbr
 
 define Package/pbr/install
 $(call Package/pbr/default/install,$(1))
@@ -133,7 +136,7 @@ define Package/pbr/prerm
 	if [ -z "$${IPKG_INSTROOT}" ]; then
 		uci -q delete firewall.pbr || true
 		echo "Stopping pbr service... "
-		/etc/init.d/pbr stop && echo "OK" || echo "FAIL"
+		/etc/init.d/pbr stop quiet && echo "OK" || echo "FAIL"
 		echo -n "Removing rc.d symlink for pbr... "
 		/etc/init.d/pbr disable && echo "OK" || echo "FAIL"
 	fi
@@ -165,7 +168,7 @@ define Package/pbr-iptables/prerm
 	if [ -z "$${IPKG_INSTROOT}" ]; then
 		uci -q delete firewall.pbr || true
 		echo "Stopping pbr-iptables service... "
-		/etc/init.d/pbr stop && echo "OK" || echo "FAIL"
+		/etc/init.d/pbr stop quiet && echo "OK" || echo "FAIL"
 		echo -n "Removing rc.d symlink for pbr-iptables... "
 		/etc/init.d/pbr disable && echo "OK" || echo "FAIL"
 	fi
@@ -188,7 +191,7 @@ define Package/pbr-netifd/prerm
 	if [ -z "$${IPKG_INSTROOT}" ]; then
 		uci -q delete firewall.pbr || true
 		echo "Stopping pbr-netifd service... "
-		/etc/init.d/pbr stop && echo "OK" || echo "FAIL"
+		/etc/init.d/pbr stop quiet && echo "OK" || echo "FAIL"
 		echo -n "Removing rc.d symlink for pbr... "
 		/etc/init.d/pbr disable && echo "OK" || echo "FAIL"
 	fi
